roles:
- components: [XYPanel]
  name: minecraft_banner_top
- components: [RichText]
  name: headline
- components: [RichText]
  name: subheadline
- components: [XYPanel]
  name: minecraft_banner_bottom
